// Error
export const GET_ERROR = "GET_ERROR";
// category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
// brand
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
// SubCategory
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const GET_ONE_SUBCATEGORY = "GET_ONE_SUBCATEGORY";
// Product
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const GET_ALL_PRODUCTS_CATEGORY = "GET_ALL_PRODUCTS_CATEGORY";
export const GET_ALL_PRODUCTS_BRAND = "GET_ALL_PRODUCTS_BRAND";
// authentification
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
// GET DATA DE USER
export const GET_CURERNT_USER = "GET_CURERNT_USER";
// forget password
export const FOREGT_PASSWORD = "FOREGT_PASSWORD";
// verify password
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
// RESET password
export const RESET_PASSWORD = "RESET_PASSWORD";
// Review
export const CREATE_REVIEW = "CREATE_REVIEW";
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
// wishlist
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const USER_WISHLIST = "USER_WISHLIST";
// Coupon
export const ADD_COUPON = "ADD_COUPON";
export const EDIT_COUPON = "EDIT_COUPON";
export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const GET_ONE_COUPON = "GET_ONE_COUPON";
export const DELTET_COUPON = "DELTET_COUPON";
// Address
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const GET_ALL_USER_ADDRESS = "GET_ALL_USER_ADDRESS";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS";
export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS";
// update user profile and pass
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
// cart
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_ALL_USER_CART = "GET_ALL_USER_CART";
export const CLEAR_ALL_USER_CART = "CLEAR_ALL_USER_CART";
export const UPDATE_ITEM_FROMCART = "UPDATE_ITEM_FROMCART";
export const DELETE_ITEM_FROMCART = "DELETE_ITEM_FROMCART";
export const APPALY_COUPON_CART = "APPALY_COUPON_CART";
// Checkout
export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH";
export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_ONE_ORDER = "GET_ONE_ORDER";
export const UPDATE_ORDER_PAY = "UPDATE_ORDER_PAY";
export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER";
export const CREATE_ORDER_CARD = "CREATE_ORDER_CARD"